;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		consult-yank-from-kill-ring
		electric-newline-and-maybe-indent
		eval-last-sexp
		ignore
		indent-for-tab-command
		mc/vertical-align
		org-beginning-of-line
		org-cycle
		org-delete-char
		org-end-of-line
		org-self-insert-command
		quick-copy-line
		rectangle-mark-mode
		rjsx-delete-creates-full-tag
		rjsx-electric-gt
		rjsx-electric-lt
		))

(setq mc/cmds-to-run-once
      '(
		backward-sexp
		consult-line
		hydra-multi-cursor/mc/mark-next-like-this
		hydra-multi-cursor/mc/mark-previous-like-this
		hydra-multi-cursor/nil
		lsp-execute-code-action
		lsp-ui-doc--handle-mouse-movement
		lsp-ui-peek-find-references
		move-to-window-line-top-bottom
		next-error
		previous-error
		prog-indent-sexp
		undo-tree-visualize
		))
